#first the version docker --version "number" ->translaet to compose file format
version: "3.5"

#networks:
  #creates a network
 # inception_network:
    #driver: bridge
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    #networks:
    #  - inception_network
    ports:
      - 443:443
    #these are the ports we can now use in the local machines browser
    restart: unless-stopped

#   wordpress:
#     image: wordpress:latest
#     #hier steht eigentlich build -> pfad zu custom Dockerfile
#     #vielleicht kann man es dann bei Dockerhub finden, wie es aussieht...
#     depends_on:
#       - db
#       #to avoid wordpress to connect to the db efore its ready
#       #keeps the service from starting until another one is ready
#     restart: unless-stopped
#     volumes:
#       - wp_data:/var/www/html
#       #da wird psaeter bestimmt ein anderer Ordner sein
#     #this means we're picking the folder we actually want to live outside safely in wp_data
#     ports:
#       - 9000:9000
#     environment:
#       #uses the ones just created in db environment
#       WORDPRESS_DB_USER: wp_user
#       WORDPRESS_DB_PASSWORD: wp_db_pass
#       WORDPRESS_DB_HOST: db:3306
#       #needs IP address and port of the mySQL server
#       #but with docker compose instead of IP one can use the service name - db
#   db:
#     image: mariadb:latest
#     restart: unless-stopped
#     volumes:
#       - db_data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root_pass
#       #wrong syntax
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wp_user
#       MYSQL_PASSWORD: wp_db_password



# volumes:
#   wp_data:
#   db_data: