#first the version docker --version "number" ->translaet to compose file format
version: "3.5"

networks:
  #creates a network
 inception_network:
    driver: bridge
services:
  nginx:
    networks:
     - inception_network
    container_name: nginx
    build: ./requirements/nginx
    #creates an image based on the Dockerfile
    ports:
      - 443:443
      #these are the ports we can now use in the local machines browser
    volumes:
      - wp_data:/var/www/wordpress:delegated
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    networks:
     - inception_network
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress:delegated
      #delegated to speed up on mac os filesystems
      #this means we're picking the folder we actually want to live outside safely in wp_data
    depends_on:
      - db
    restart: unless-stopped

  db:
    networks:
     - inception_network
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      #important to not wipe all the data and instead store it locally
    restart: unless-stopped
      
volumes:
  wp_data:
    driver: local
    driver_opts:
      device: "/home/rschleic/data/wordpress"
      type: none
      o: bind

  db_data:
    driver: local
    driver_opts:
      device: "/home/rschleic/data/mariadb"
      type: none
      o: bind
#everything that gets changed in db and wp will be redirected to this created folder on the local machine