#first the version docker --version "number" ->translaet to compose file format
version: "3.5"

networks:
  #creates a network
 inception_network:
    driver: bridge
services:
  nginx:
    container_name: nginx
    # image: nginx
    build: ./requirements/nginx
    networks:
     - inception_network
    ports:
      - 443:443
    #these are the ports we can now use in the local machines browser

    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    #hier steht eigentlich build -> pfad zu custom Dockerfile
    #vielleicht kann man es dann bei Dockerhub finden, wie es aussieht...
    networks:
     - inception_network
    depends_on:
      - db
      #to avoid wordpress to connect to the db efore its ready
      #keeps the service from starting until another one is ready
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html:delegated
      #delegated to speed up on mac os filesystems
      #da wird psaeter bestimmt ein anderer Ordner sein
    #this means we're picking the folder we actually want to live outside safely in wp_data
    env_file:
      - .env
    #environment:
      #uses the ones just created in db environment
      #WORDPRESS_DB_USER: wp_user
      #WORDPRESS_DB_PASSWORD: wp_db_pass
      #WORDPRESS_DB_HOST: db:3306
      #needs IP address and port of the mySQL server
      #but with docker compose instead of IP one can use the service name - db
  db:
    container_name: mariadb
    # image: nginx
    env_file:
      - .env
    build: ./requirements/mariadb
    networks:
     - inception_network
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      #important to not wipe all the data and insted store it locally
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_db_password
    # ports:
    #   - 3306:3306
    #no ports!!

      
  # php:
  #   image: php:7.4-fpm-alpine
  #   volumes:
  #     - wp_data:/var/www/html:delegated




volumes:
  wp_data:
    driver: local
    driver_opts:
      device: "/home/rschleic/data/wordpress"
      type: none
      o: bind

  db_data:
    driver: local
    driver_opts:
      device: "/home/rschleic/data/mariadb"
      type: none
      o: bind
#everything that gets changed in db and wp will be redirected to this created folder on the local machine